---
# Source: egov-notification-mail/templates/service.yaml
# service.yaml---
apiVersion: v1
kind: Service
metadata:
  name: ddouiapp
  namespace: default
  annotations: 
  labels:
    app: ddouiapp     
    group: core   
spec:
  selector:
    app: ddouiapp  
    group: core    
  ports:
  - port: 80
    targetPort: 8080
---
# Source: egov-notification-mail/templates/deployment.yaml
# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ddouiapp
  namespace: default
  labels:
    app: ddouiapp     
    group: core   
spec:
  selector:
    matchLabels:
      app: ddouiapp
      group: core
  strategy:
    rollingUpdate:
      maxUnavailable: 0     
  replicas: 1
  template:
    metadata:  
      annotations:      
        deployment-timestamp: "20201207163000"        
      labels:
        app: ddouiapp   
        group: core  
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              topologyKey: "failure-domain.beta.kubernetes.io/zone"
              labelSelector:
                matchLabels:
                  app: ddouiapp     
                  group: core 
      initContainers:             
      containers:      
        - name: ddouiapp
          image: pedireddysaikiran/testddoui:latest
          imagePullPolicy: IfNotPresent             
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          ports:
            - name: https
              containerPort: 8080
              protocol: TCP
          lifecycle:
            preStop:
              exec:
                command:
                - sh
                - -c
                - sleep 10 
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: default
  labels:
    app: ddouiapp
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
  name: ddouiapp
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: 'ddouiapp'
          servicePort: 80
    host: test.ddoui.com
  tls:
  - hosts:
    - test.ddoui.com               
                



